//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sep4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datapoint
    {
        public int DatapointID { get; set; }
        public int SaunaID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Temperature { get; set; }
        public string Co2 { get; set; }
        public string Humidity { get; set; }
        public string ServoSettingAtTime { get; set; }
    
        public virtual Sauna Sauna { get; set; }
    }
}
