//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sep4
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaunaFact
    {
        public int SaunaDimID { get; set; }
        public int ReservationDimID { get; set; }
        public int SupervisorDimID { get; set; }
        public int EstablishmentDimID { get; set; }
        public int UserDimID { get; set; }
        public int DateDimID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Temperature { get; set; }
        public int CO2 { get; set; }
        public Nullable<int> Humidity { get; set; }
        public string ServoSettingAtTime { get; set; }
    
        public virtual DateDim DateDim { get; set; }
        public virtual EstablishmentDim EstablishmentDim { get; set; }
        public virtual ReservationDim ReservationDim { get; set; }
        public virtual SaunaDim SaunaDim { get; set; }
        public virtual SupervisorDim SupervisorDim { get; set; }
        public virtual UserDim UserDim { get; set; }
    }
}
