//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sep4
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageSupervisorDim
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> EstShiftFromDate { get; set; }
        public Nullable<System.DateTime> EstShiftToDate { get; set; }
        public string Rights { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
    }
}
